app:
  chat-id-secret-key: /bot/telegram/chat
  bot-token: /bot/telegram/token
  bot-name: "@cmw22_finance_bot"

commands:
  status: "/status"
  help: "/help"

quarkus:
  rest-client:
    telegram:
      url: https://api.telegram.org
      connect-timeout: 2000
      read-timeout: 10000
  cache:
    enabled: true
    caffeine:
      "ssm-secrets":
        expire-after-write: 1h
  log:
    level: INFO
    min-level: DEBUG
    console:
      enable: true
      format: '%d{HH:mm:ss.SSS} %-5p (%-10t) [%c{2.}] %s%e%n'
    category:
      "com.yuriytkach":
        level: DEBUG

"%dev":
  quarkus:
    log:
      min-level: TRACE
      console:
        darken: 1
      category:
        "com.yuriytkach":
          level: TRACE
    aws:
      devservices:
        localstack:
          init-completion-msg: 'SSM parameters created'
          init-scripts-folder: '.local-scripts'
