ai:
  lambda:
    function-name: lambda-ai-service

bot:
  telegram:
    secret-name: /bot/telegram/secret

quarkus:
  rest-client:
    telegram-bot:
      url: https://cmw22-bot.yuriytkach.com
      connect-timeout: 2000
      read-timeout: 30000
  log:
    level: INFO
    min-level: DEBUG
    console:
      enable: true
      format: '%d{HH:mm:ss.SSS} %-5p (%-10t) [%c{2.}] %s%e%n'
    category:
      "com.yuriytkach":
        level: DEBUG

"%dev":
  quarkus:
    log:
      min-level: TRACE
      console:
        darken: 1
      category:
        "com.yuriytkach":
          level: TRACE
    aws:
      devservices:
        localstack:
          init-completion-msg: 'SSM parameters created'
          init-scripts-folder: '.local-scripts'

"%test":
  quarkus:
    log:
      min-level: TRACE
      category:
        "com.yuriytkach":
          level: TRACE
