app:
  aws-config-key:
    openapi: /ai/chatgpt

quarkus:
  langchain4j:
    openai:
      api-key: 'api-key'
      timeout: 60s
      chat-model:
        temperature: 0.5
        model-name: gpt-4
  log:
    level: INFO
    min-level: DEBUG
    console:
      enable: true
      format: '%d{HH:mm:ss.SSS} %-5p (%-10t) [%c{2.}] %s%e%n'
    category:
      "com.yuriytkach":
        level: DEBUG

"%dev":
  quarkus:
    log:
      console:
        darken: 1
    aws:
      devservices:
        localstack:
          init-completion-msg: 'SSM parameters created'
          init-scripts-folder: '/home/yuriy/workspace/bank-accounts-track-bot/.local-scripts'

"%test":
  quarkus:
    log:
      min-level: TRACE
      category:
        "com.yuriytkach":
          level: TRACE
