quarkus:
  cache:
    caffeine:
      "fund-status":
        expire-after-write: 120s
  log:
    level: INFO
    min-level: DEBUG
    console:
      enable: true
      format: '%d{HH:mm:ss.SSS} %-5p (%-10t) [%c{2.}] %s%e%n'
    category:
      "com.yuriytkach":
        level: DEBUG
