reporter:
  month-before: 1
  name-stop-words:
    - Visa
    - Banking
    - Mobile
    - From
    - Payment

txfetcher:
  privat:
    config-key: /batb/tx/privat/config
  mono-token:
    config-key: /batb/tx/mono-token/config

translation:
  lambda:
    function-name: lambda-ai-service

quarkus:
  rest-client:
    privatbank:
      url: https://acp.privatbank.ua
      connect-timeout: 2000
      read-timeout: 10000
    monobank:
      url: https://api.monobank.ua
      connect-timeout: 2000
      read-timeout: 140000
  log:
    level: INFO
    min-level: DEBUG
    console:
      enable: true
      format: '%d{HH:mm:ss.SSS} %-5p (%-10t) [%c{2.}] %s%e%n'
    category:
      "com.yuriytkach":
        level: DEBUG

"%dev":
  quarkus:
    log:
      min-level: TRACE
      console:
        darken: 1
      category:
        "com.yuriytkach":
          level: TRACE
    aws:
      devservices:
        localstack:
          init-completion-msg: 'SSM parameters created'
          init-scripts-folder: '.local-scripts'

"%test":
  quarkus:
    log:
      min-level: TRACE
      category:
        "com.yuriytkach":
          level: TRACE
