reporter:
  month-before: 1
  name-stop-words:
    - Visa
    - Banking
    - Mobile
    - From
    - Payment
  replacers:
    '–ö–ª–∏–º–∞–Ω—Å—å–∫–∞ –û–ª—å–≥–∞': 'SendPulse'
  donation-stats-notification-message: |
    üìä *–°—Ç–∞—Ç–∏—Å—Ç–∏–∫–∞ –¥–æ–Ω–∞—Ç—ñ–≤ –∑–∞ –ø–æ–ø–µ—Ä–µ–¥–Ω—ñ–π –º—ñ—Å—è—Ü—å*:
    
    üí∞ *–ó–∞–≥–∞–ª—å–Ω–∞ —Å—É–º–∞ –¥–æ–Ω–∞—Ç—ñ–≤:* %,.2f –≥—Ä–Ω
    #Ô∏è‚É£ *–ö—ñ–ª—å–∫—ñ—Å—Ç—å —Ç—Ä–∞–Ω–∑–∞–∫—Ü—ñ–π:* %d
    üèÜ *–ú–∞–∫—Å–∏–º–∞–ª—å–Ω–∏–π –¥–æ–Ω–∞—Ç:* %,.2f –≥—Ä–Ω
    ü™ô *–ú—ñ–Ω—ñ–º–∞–ª—å–Ω–∏–π –¥–æ–Ω–∞—Ç:* %,.2f –≥—Ä–Ω
    
    üìà *–ú–µ–¥—ñ–∞–Ω–∞:* %,.2f (—Ç–æ–±—Ç–æ 50%% –¥–æ–Ω–∞—Ç—ñ–≤ –±—ñ–ª—å—à–∞ –∑–∞ —Ü—é —Å—É–º—É)
    üìâ *p10:* %,.2f (—Ç–æ–±—Ç–æ 10%% –¥–æ–Ω–∞—Ç—ñ–≤ –º–µ–Ω—à–µ –∞–±–æ —Ä—ñ–≤–Ω—ñ —Ü—ñ–π —Å—É–º—ñ)
    ü•á *p90:* %,.2f (—Ç–æ–±—Ç–æ 10%% –¥–æ–Ω–∞—Ç—ñ–≤ –±—ñ–ª—å—à–µ –∞–±–æ —Ä—ñ–≤–Ω—ñ —Ü—ñ–π —Å—É–º—ñ)
    
    ‚ñ∂Ô∏è‚ñ∂Ô∏è‚ñ∂Ô∏è
    
    üï∫ *–ö—ñ–ª—å–∫—ñ—Å—Ç—å –¥–æ–Ω–∞—Ç—ñ–≤ –≤—ñ–¥ –æ–¥–Ω—ñ—î—ó –æ—Å–æ–±–∏* (—Å–µ—Ä–µ–¥ —Ç–∏—Ö, –¥–µ –≤–¥–∞–ª–æ—Å—å –≤–∏–∑–Ω–∞—á–∏—Ç–∏ —ó–º º—è):
    
    üë• *–£–Ω—ñ–∫–∞–ª—å–Ω—ñ –¥–æ–Ω–∞—Ç–µ—Ä–∏:* %d
    üîù *–ú–∞–∫—Å–∏–º–∞–ª—å–Ω–∞ –∫—ñ–ª—å–∫—ñ—Å—Ç—å –¥–æ–Ω–∞—Ç—ñ–≤ –≤—ñ–¥ –æ–¥–Ω—ñ—î—ó –æ—Å–æ–±–∏:* %d
    üîΩ *–ú—ñ–Ω—ñ–º–∞–ª—å–Ω–∞:* %d
    
    üìà *–ú–µ–¥—ñ–∞–Ω–∞:* %.0f (—Ç–æ–±—Ç–æ 50%% –¥–æ–Ω–∞—Ç–∏–ª–∏ —Å—Ç—ñ–ª—å–∫–∏ –∞–±–æ –±—ñ–ª—å—à–µ —Ä–∞–∑—ñ–≤)
    ü•á *p90:* %.0f (—Ç–æ–±—Ç–æ 10%% –¥–æ–Ω–∞—Ç–∏–ª–∏ —Å—Ç—ñ–ª—å–∫–∏ –∞–±–æ –±—ñ–ª—å—à–µ —Ä–∞–∑—ñ–≤)
    
    #donation_stats

txfetcher:
  privat:
    config-key: /batb/tx/privat/config
  mono-token:
    config-key: /batb/tx/mono-token/config

ai:
  lambda:
    function-name: lambda-ai-service

bot:
  telegram:
    secret-name: /bot/telegram/secret

quarkus:
  rest-client:
    privatbank:
      url: https://acp.privatbank.ua
      connect-timeout: 2000
      read-timeout: 10000
    monobank:
      url: https://api.monobank.ua
      connect-timeout: 2000
      read-timeout: 140000
    telegram-bot:
      url: https://cmw22-bot.yuriytkach.com
      connect-timeout: 2000
      read-timeout: 30000
  log:
    level: INFO
    min-level: DEBUG
    console:
      enable: true
      format: '%d{HH:mm:ss.SSS} %-5p (%-10t) [%c{2.}] %s%e%n'
    category:
      "com.yuriytkach":
        level: DEBUG

"%dev":
  quarkus:
    log:
      min-level: TRACE
      console:
        darken: 1
      category:
        "com.yuriytkach":
          level: TRACE
    aws:
      devservices:
        localstack:
          init-completion-msg: 'SSM parameters created'
          init-scripts-folder: '.local-scripts'

"%test":
  quarkus:
    log:
      min-level: TRACE
      category:
        "com.yuriytkach":
          level: TRACE
